# Generated by Django 4.0.6 on 2022-07-12 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mos',
            old_name='gunGbcd',
            new_name='branch',
        ),
        migrations.RenameField(
            model_name='mos',
            old_name='gsteukgiCd',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='mos',
            old_name='gsteukgiNm',
            new_name='name',
        ),
        migrations.CreateModel(
            name='recurit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recuritYear', models.IntegerField()),
                ('recuritRound', models.IntegerField()),
                ('enlistMilitaryUnit', models.CharField(max_length=150)),
                ('recuritCnt', models.IntegerField()),
                ('applyedCnt', models.IntegerField()),
                ('recuritStart', models.IntegerField()),
                ('recuritEnd', models.IntegerField()),
                ('enlistStart', models.IntegerField()),
                ('enlistEnd', models.IntegerField()),
                ('mos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mos.mos')),
            ],
        ),
    ]
