# Generated by Django 4.0.6 on 2022-07-13 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mos', '0002_rename_gungbcd_mos_branch_rename_gsteukgicd_mos_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wiki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('modifier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('mos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mos.mos')),
            ],
        ),
        migrations.AddField(
            model_name='mos',
            name='currentWiki',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_Wiki_doc', to='mos.wiki'),
        ),
    ]
