# Generated by Django 4.0.6 on 2022-07-17 05:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mos', '0004_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=150)),
                ('level', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='UserPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mos.point')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MosPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direct', models.BooleanField()),
                ('mos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mos.mos')),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mos.point')),
            ],
        ),
        migrations.CreateModel(
            name='MMAPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=300)),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mos.point')),
            ],
        ),
    ]
