# Generated by Django 4.0.6 on 2022-07-17 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mos', '0005_point_userpoint_mospoint_mmapoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='level',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
