# Generated by Django 4.0.6 on 2022-08-21 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mos', '0007_alter_point_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MosReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating1', models.IntegerField()),
                ('rating2', models.IntegerField()),
                ('rating3', models.IntegerField()),
                ('rating4', models.IntegerField()),
                ('rating5', models.IntegerField()),
                ('review', models.TextField()),
                ('advantage', models.TextField()),
                ('disadvantage', models.TextField()),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('mos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mos.mos')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
